spring.application.name=spring-jms-demo

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.pub-sub-domain=true
# false for Queue, true for Topic

file.upload-dir=/Users/himanshu/Desktop/image_dir


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB